package com.tigo.gt.ws.authservices;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

public class AuthServicePortClient
{
  @WebServiceRef
  private static AuthenticationService authenticationService;

  public static void main(String [] args)
  {
    authenticationService = new AuthenticationService();
    AuthService authService = authenticationService.getAuthServicePort();
    // Add your code to call the desired methods.
  }
}
