package com.tigo.gt.ws.authservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebService(wsdlLocation="http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl",
  targetNamespace="http://authservices.ws.gt.tigo.com/", name="AuthService")
@XmlSeeAlso(
  { com.tigo.gt.ws.authservices.ObjectFactory.class })
@SOAPBinding(style=Style.RPC)
public interface AuthService
{
  @WebMethod
  @Action(input="http://authservices.ws.gt.tigo.com/AuthService/requestUserInfo",
    output="http://authservices.ws.gt.tigo.com/AuthService/requestUserInfoResponse")
  @WebResult(partName="userInfo", name="userInfo")
  public com.tigo.gt.ws.authservices.UserInformationResponse requestUserInfo(@WebParam(partName="ldapId",
      name="ldapId")
    int ldapId, @WebParam(partName="user", name="user")
    String user, @WebParam(partName="password", name="password")
    String password);
}
