package com.tigo.gt.ws.authservices;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl",
  targetNamespace="http://authservices.ws.gt.tigo.com/", name="AuthenticationService")
public class AuthenticationService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.tigo.gt.ws.authservices.AuthenticationService");
      URL baseUrl = AuthenticationService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            AuthenticationService.class.getResource("http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://DSFCIS-SRV:8380/authservices/AuthService/#%7Bhttp%3A%2F%2Fauthservices.ws.gt.tigo.com%2F%7DAuthenticationService?wsdl",
          e);
    }
  }

  public AuthenticationService()
  {
    super(wsdlLocationURL,
          new QName("http://authservices.ws.gt.tigo.com/", "AuthenticationService"));
  }

  public AuthenticationService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="AuthServicePort")
  public com.tigo.gt.ws.authservices.AuthService getAuthServicePort()
  {
    return (com.tigo.gt.ws.authservices.AuthService) super.getPort(new QName("http://authservices.ws.gt.tigo.com/",
                                                                             "AuthServicePort"),
                                                                   com.tigo.gt.ws.authservices.AuthService.class);
  }

  @WebEndpoint(name="AuthServicePort")
  public com.tigo.gt.ws.authservices.AuthService getAuthServicePort(WebServiceFeature... features)
  {
    return (com.tigo.gt.ws.authservices.AuthService) super.getPort(new QName("http://authservices.ws.gt.tigo.com/",
                                                                             "AuthServicePort"),
                                                                   com.tigo.gt.ws.authservices.AuthService.class,
                                                                   features);
  }
}
