package com.blve.smschat.domain;

// Generated 23-jun-2013 14:08:36 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SubscribebTbl generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBEB_TBL", schema = "BLVE" )
public class SubscribebTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1176005931556197383L;
	
	private Integer subscribebid;
	private static SubscribeaTbl subscribeaTbl;
	private String alias;
	private String estado;
	private String msisdn;
	private Date fechacobro;
	private Date fechaultimaactividad;
	private Date fechacreacion;

	public SubscribebTbl() {
	}

	public SubscribebTbl(Integer subscribebid, SubscribeaTbl subscribeaTbl) {
		this.subscribebid = subscribebid;
		this.subscribeaTbl = subscribeaTbl;
	}

	public SubscribebTbl(Integer subscribebid, SubscribeaTbl subscribeaTbl,
			String alias, String estado, String msisdn,
			Date fechacobro, Date fechaultimaactividad,
			Date fechacreacion) {
		this.subscribebid = subscribebid;
		this.subscribeaTbl = subscribeaTbl;
		this.alias = alias;
		this.estado = estado;
		this.msisdn = msisdn;
		this.fechacobro = fechacobro;
		this.fechaultimaactividad = fechaultimaactividad;
		this.fechacreacion = fechacreacion;
	}

	@Id
	@Column(name = "SUBSCRIBEBID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name="SubscritorBSeqId",sequenceName="SEQ_SUBSCRIBEB_TBL", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SubscritorBSeqId")
	public Integer getSubscribebid() {
		return this.subscribebid;
	}

	public void setSubscribebid(Integer subscribebid) {
		this.subscribebid = subscribebid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBEAID", nullable = false)
	public SubscribeaTbl getSubscribeaTbl() {
		return this.subscribeaTbl;
	}

	public void setSubscribeaTbl(SubscribeaTbl subscribeaTbl) {
		this.subscribeaTbl = subscribeaTbl;
	}

	@Column(name = "ALIAS", length = 20)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "ESTADO", length = 15)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "MSISDN", length = 9)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "FECHACOBRO")
	public Date getFechacobro() {
		return this.fechacobro;
	}

	public void setFechacobro(Date fechacobro) {
		this.fechacobro = fechacobro;
	}

	@Column(name = "FECHAULTIMAACTIVIDAD")
	public Date getFechaultimaactividad() {
		return this.fechaultimaactividad;
	}

	public void setFechaultimaactividad(Date fechaultimaactividad) {
		this.fechaultimaactividad = fechaultimaactividad;
	}

	@Column(name = "FECHACREACION")
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

}
