<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/LoggerDBConnector/LoggerDBAdapter/DBAdapter" name="DBAdapter-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/LoggerDBConnector/LoggerDBAdapter/DBAdapter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/LoggerDBConnector/LoggerDBAdapter/DBAdapter" location="../adapter/LoggerDBAdapter/DBAdapter.wsdl"/>
  <binding name="DBAdapter_ptt-binding" type="tns:DBAdapter_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="DBAdapter">
      <soap:operation soapAction="DBAdapter"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="DBAdapter-service">
    <port name="DBAdapter-port" binding="tns:DBAdapter_ptt-binding">
      <soap:address location="jca://eis/DB/EAuditError"/>
    </port>
  </service>
</definitions>